#!/usr/bin/env bash
#
# build-sap.sh — Build the SAP signing bridge for iOS (arm64).
#
# Produces, under $SAP_OUT (default: this script's directory/build):
#   libunicorn.a   static Unicorn 2.1.x engine (x86-64 guest), ios-arm64
#   libsap.a       c-archive exposing SapInit/SapSign/SapLastError/SapClose/SapFree
#   sap.h          C header generated by go -buildmode=c-archive
#
# The Xcode project (project.yml) links both static libraries and includes sap.h.
# No host JIT is required: Unicorn is an interpreter and the guest (Apple's
# private CommerceKit) runs emulated inside the app process.
#
# Requirements (CI macos-15 with Xcode): git, cmake, clang, go >= 1.25.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

SAP_OUT="${SAP_OUT:-$SCRIPT_DIR/build}"
# v0.4.0：换 Naville/unicorn feature/tci 分支——在 unicorn 2.x（QEMU 5.0.1）上
# 恢复了 QEMU TCI（Tiny Code Interpreter，纯 C 解释执行 TCG 中间表示）。
# 解释器不写可执行内存 → 无需 JIT/CODESIGNING 权限 → iOS 27 beta + 无 StikDebug
# 也能跑（用户 .ips 实锤 TCG 路线在该环境必死）。性能慢 10-30x，SAP 短会话可接受。
# 上游参考：Naville/unicorn feature/tci + 1rhino2/unicorn-tci（fnprint 生产使用）。
UNICORN_REPO="${UNICORN_REPO:-https://github.com/Naville/unicorn.git}"
UNICORN_BRANCH="${UNICORN_BRANCH:-feature/tci}"
UNICORN_SRC="${UNICORN_SRC:-$SCRIPT_DIR/.unicorn-src}"
UNICORN_BUILD="${UNICORN_BUILD:-$SCRIPT_DIR/.unicorn-build-tci}"
GO="${GO:-go}"

mkdir -p "$SAP_OUT"

# 跨 run artifact 缓存命中（CI 已还原 libsap.a + sap.h + .openlist-src）→ 全部跳过。
# 省下：OpenList clone + 前端下载 + go mod tidy/依赖下载 + 167MB 归档编译 ≈ 3.5 分钟。
if [ -f "$SAP_OUT/libsap.a" ] && [ -f "$SAP_OUT/sap.h" ]; then
  echo "==> 缓存命中：libsap.a + sap.h 已存在，跳过 Unicorn/OpenList/Go 全部构建"
  ls -la "$SAP_OUT/libsap.a" "$SAP_OUT/sap.h"
  exit 0
fi

echo "==> [1/5] Preparing Unicorn $UNICORN_TAG source"
# 产物已存在（跨 run artifact 缓存命中）时连源码克隆都跳过——克隆仅编译需要。
if [ ! -f "$UNICORN_BUILD/libunicorn.a" ]; then
  if [ ! -d "$UNICORN_SRC/.git" ]; then
    rm -rf "$UNICORN_SRC"
    git clone --depth 1 --branch "$UNICORN_BRANCH" "$UNICORN_REPO" "$UNICORN_SRC"
  fi
  # v0.3.3 更正：曾尝试注入 --enable-tcg-interpreter 走 QEMU TCI 纯解释器
  #（无 JIT 也能跑），但 unicorn 2.1.0 的 configure 实际不含该选项
  #（"ERROR: unknown option"，948 行只是上游 QEMU 遗留注释），TCI 路线不通。
  # Unicorn 2.x 默认 TCG 就是 JIT（Apple 平台 pthread_jit_write_protect_np），
  # 因此 SAP 签名必须有 JIT：Swift 侧 JIT 探测作硬闸门（未启用 → 不进模拟器、
  # 明确报错引导 StikDebug），避免 TCG 在无 JIT 进程里写可执行内存直接崩。
fi

echo "==> [2/5] Building libunicorn.a for ios-arm64 (static, x86-64 guest)"
if [ ! -f "$UNICORN_BUILD/libunicorn.a" ]; then
  mkdir -p "$UNICORN_BUILD"
  cmake -S "$UNICORN_SRC" -B "$UNICORN_BUILD" \
    -G Ninja \
    -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_ARCHITECTURES=arm64 \
    -DCMAKE_OSX_SYSROOT=iphoneos \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DBUILD_SHARED_LIBS=OFF \
    -DUNICORN_BUILD_TESTS=OFF \
    -DUNICORN_BUILD_SAMPLES=OFF \
    -DUNICORN_INTERPRETER=on \
    -DUC_ARCH=x86_64 \
    -DUC_MODE=x86_64
  cmake --build "$UNICORN_BUILD" -j"$(sysctl -n hw.ncpu 2>/dev/null || echo 4)"
fi

UNICORN_LIB="$UNICORN_BUILD/libunicorn.a"
UNICORN_INC="$UNICORN_SRC/include"
[ -f "$UNICORN_LIB" ] || { echo "error: $UNICORN_LIB not produced"; exit 1; }
[ -f "$UNICORN_INC/unicorn/unicorn.h" ] || { echo "error: unicorn headers missing at $UNICORN_INC"; exit 1; }
cp "$UNICORN_LIB" "$SAP_OUT/libunicorn.a"

echo "==> [3/5] Preparing OpenList source (pinned ${OPENLIST_VER:-v4.2.6}, 方案 A 单 runtime)"
# OpenList 与 Sap* 合并为单一 Go runtime（v0.3.73）：dlopen 第二 runtime 初始化即崩
# （run.log 实锤），改为静态链接进宿主。源码 pin 到 tag 保证可重现，前端 dist 内嵌。
OPENLIST_SRC="${OPENLIST_SRC:-$SCRIPT_DIR/.openlist-src}"
OPENLIST_VER="${OPENLIST_VER:-v4.2.6}"
OPENLIST_REPO="${OPENLIST_REPO:-https://github.com/OpenListTeam/OpenList.git}"
if [ ! -f "$OPENLIST_SRC/public/dist/index.html" ]; then
  rm -rf "$OPENLIST_SRC"
  git clone --depth 1 --branch "$OPENLIST_VER" "$OPENLIST_REPO" "$OPENLIST_SRC"
  mkdir -p "$OPENLIST_SRC/public/dist"
  curl -fsSL "https://github.com/OpenListTeam/OpenList-Frontend/releases/download/${OPENLIST_VER}/openlist-frontend-dist-${OPENLIST_VER}.tar.gz" \
    | tar -xz -C "$OPENLIST_SRC/public/dist"
fi
[ -f "$OPENLIST_SRC/public/dist/index.html" ] || { echo "error: openlist frontend dist missing"; exit 1; }

echo "==> [3.5/5] Injecting bootstrap stage markers (v0.3.86 崩溃定位)"
# 给 OpenList 源码的 bootstrap/db 各函数注入 begin/done 标记（写到模块数据目录，
# SSH `mlog` 可读），崩溃后对照标记存在性即可函数级定位。幂等：已注入则跳过。
python3 "$SCRIPT_DIR/patch_stages.py" "$OPENLIST_SRC" || echo "?? 标记注入失败（继续未打补丁构建）"
"$(command -v gofmt || echo gofmt)" -w "$OPENLIST_SRC/internal/bootstrap" "$OPENLIST_SRC/internal/db" 2>/dev/null || true
# replace 指向本地源码（嵌入 dist 必须可控）；go.sum 由下方 tidy 解析
"$GO" mod edit -require=github.com/OpenListTeam/OpenList/v4@"$OPENLIST_VER"
"$GO" mod edit -replace=github.com/OpenListTeam/OpenList/v4="$OPENLIST_SRC"

echo "==> [4/5] Resolving Go module graph"
export GOPROXY="${GOPROXY:-https://proxy.golang.org,direct}"
export GOFLAGS="${GOFLAGS:-}"
"$GO" mod tidy

echo "==> [5/5] Building libsap.a (c-archive, ios/arm64, Sap* + OpenListMain)"
# Go's GOOS=ios CGO pipeline auto-configures clang/SDK; we only add the Unicorn
# include and link paths. CGO_LDFLAGS carries -lunicorn for the final link.
#
# NOTE: with -buildmode=c-archive, cgo names the generated header after the
# archive's base name — `-o libsap.a` yields libsap.a + **libsap.h**, never sap.h.
# So emit as sap.a (giving us the sap.h that EscapeOS-Bridging-Header.h includes),
# then rename the archive to libsap.a because -lsap looks for that exact name.
CGO_ENABLED=1 \
GOOS=ios GOARCH=arm64 \
CGO_CFLAGS="-I$UNICORN_INC" \
CGO_LDFLAGS="-L$UNICORN_BUILD -lunicorn" \
"$GO" build -buildmode=c-archive \
  -ldflags="-s -w -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.Version=${OPENLIST_VER#v}' -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.WebVersion=$OPENLIST_VER'" \
  -o "$SAP_OUT/sap.a" .

[ -f "$SAP_OUT/sap.a" ] || { echo "error: sap.a not produced"; exit 1; }
[ -f "$SAP_OUT/sap.h" ] || { echo "error: sap.h not produced"; exit 1; }
mv -f "$SAP_OUT/sap.a" "$SAP_OUT/libsap.a"

echo "==> Done. Artifacts in $SAP_OUT:"
ls -la "$SAP_OUT"/libsap.a "$SAP_OUT"/sap.h "$SAP_OUT"/libunicorn.a
