#!/usr/bin/env bash
#
# build-sap.sh — Build the SAP signing bridge for iOS (arm64).
#
# Produces, under $SAP_OUT (default: this script's directory/build):
#   libunicorn.a   static Unicorn 2.1.x engine (x86-64 guest), ios-arm64
#   libsap.a       c-archive exposing SapInit/SapSign/SapLastError/SapClose/SapFree
#   sap.h          C header generated by go -buildmode=c-archive
#
# The Xcode project (project.yml) links both static libraries and includes sap.h.
# No host JIT is required: Unicorn is an interpreter and the guest (Apple's
# private CommerceKit) runs emulated inside the app process.
#
# Requirements (CI macos-15 with Xcode): git, cmake, clang, go >= 1.25.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

SAP_OUT="${SAP_OUT:-$SCRIPT_DIR/build}"
UNICORN_TAG="${UNICORN_TAG:-2.1.0}"
UNICORN_SRC="${UNICORN_SRC:-$SCRIPT_DIR/.unicorn-src}"
UNICORN_BUILD="${UNICORN_BUILD:-$SCRIPT_DIR/.unicorn-build}"
GO="${GO:-go}"

mkdir -p "$SAP_OUT"

echo "==> [1/4] Preparing Unicorn $UNICORN_TAG source"
if [ ! -d "$UNICORN_SRC/.git" ]; then
  rm -rf "$UNICORN_SRC"
  git clone --depth 1 --branch "$UNICORN_TAG" https://github.com/unicorn-engine/unicorn.git "$UNICORN_SRC"
fi

echo "==> [2/4] Building libunicorn.a for ios-arm64 (static, x86-64 guest)"
if [ ! -f "$UNICORN_BUILD/libunicorn.a" ]; then
  rm -rf "$UNICORN_BUILD"
  mkdir -p "$UNICORN_BUILD"
  cmake -S "$UNICORN_SRC" -B "$UNICORN_BUILD" \
    -G Ninja \
    -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_ARCHITECTURES=arm64 \
    -DCMAKE_OSX_SYSROOT=iphoneos \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DBUILD_SHARED_LIBS=OFF \
    -DUNICORN_BUILD_TESTS=OFF \
    -DUNICORN_BUILD_SAMPLES=OFF \
    -DUC_ARCH=x86_64 \
    -DUC_MODE=x86_64
  cmake --build "$UNICORN_BUILD" -j"$(sysctl -n hw.ncpu 2>/dev/null || echo 4)"
fi

UNICORN_LIB="$UNICORN_BUILD/libunicorn.a"
UNICORN_INC="$UNICORN_SRC/include"
[ -f "$UNICORN_LIB" ] || { echo "error: $UNICORN_LIB not produced"; exit 1; }
[ -f "$UNICORN_INC/unicorn/unicorn.h" ] || { echo "error: unicorn headers missing at $UNICORN_INC"; exit 1; }
cp "$UNICORN_LIB" "$SAP_OUT/libunicorn.a"

echo "==> [3/4] Resolving Go module graph"
export GOPROXY="${GOPROXY:-https://proxy.golang.org,direct}"
export GOFLAGS="${GOFLAGS:-}"
"$GO" mod tidy

echo "==> [4/4] Building libsap.a (c-archive, ios/arm64)"
# Go's GOOS=ios CGO pipeline auto-configures clang/SDK; we only add the Unicorn
# include and link paths. CGO_LDFLAGS carries -lunicorn for the final link.
CGO_ENABLED=1 \
GOOS=ios GOARCH=arm64 \
CGO_CFLAGS="-I$UNICORN_INC" \
CGO_LDFLAGS="-L$UNICORN_BUILD -lunicorn" \
"$GO" build -buildmode=c-archive -o "$SAP_OUT/libsap.a" .

[ -f "$SAP_OUT/libsap.a" ] || { echo "error: libsap.a not produced"; exit 1; }
[ -f "$SAP_OUT/sap.h" ]    || { echo "error: sap.h not produced"; exit 1; }

echo "==> Done. Artifacts in $SAP_OUT:"
ls -la "$SAP_OUT"/libsap.a "$SAP_OUT"/sap.h "$SAP_OUT"/libunicorn.a
